### ISSUE TITLE
Nécessaire ?

### ISSUE THREAD

**Issue by froggypaule** [froggypaule/maDMP-bioimage#84]
Cette question est-elle obligatoire alors qu'il n'y a qu'une seule réponse possible

**Comment by abihouee** [comment]
Nous avons crée cette question en rapport avec le PGD Structure Génomique. Le titre n'est pas pertinent. La question concerne le type de structure : 1-a-2

**Comment by froggypaule** [comment]
désolée, mais là j'ai du mal à comprendre de quoi l'on parle ici ??? @abihouee ?

**Comment by froggypaule** [comment]
closing since I am not sure this is still relevant??
